name: Mac Build
on: 
  pull_request:
    branches:
      - main
jobs:
  Build-Test:
    runs-on: macos-latest
    steps:
      - name: "Launching the mac build workflow"
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checking out the repository
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: npm install -g yarn
      - name: Update Homebrew
        run: brew update
      - name: Install GCC along with GNU Fortran
        run: brew install gcc
      - name: Install Perl if it doesn't exit
        run: brew install perl
      - name: Install OCaml
        run: brew install ocaml
      - name: Install Opam
        run: brew install opam
      - name: Install GHC
        run: brew install ghc
      - name: Intall Zig
        run: brew install zig
      - name: Install Nim
        run: brew install nim
      - name: Install Erlang
        run: brew install erlang
      - name: Install Lua
        run: brew install lua
      - name: Install D
        run: brew install dmd
      - name: Install R
        run: brew install r
      - name: Tap Dart
        run: brew tap dart-lang/dart
      - name: Install Dart
        run: brew install dart
      - name: Install Java
        run: brew install java
      - name: Install Kotlin
        run: brew install kotlin
      - name: Install Clojure
        run: brew install clojure/tools/clojure
      - name: Install Leiningen
        run: brew install leiningen
      - name: Install Groovy
        run: brew install groovy
      - name: Install Crystal
        run: brew install crystal
      - name: Install Cobol
        run: brew install gnu-cobol
      - name: Running build
        run: ruby scripts/build.rb