name: Windows Build
on: 
  pull_request:
    branches:
      - main
jobs:
  Build-Test:
    runs-on: windows-2016
    steps:
      - name: "Launching the windows build workflow"
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checking out the repository
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: npm install -g yarn
      - name: Install Zig
        run: choco install zig
      - name: Install Dart
        run: choco install dart-sdk
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Install Julia
        run: choco install julia
      - name: Running build
        run: ruby code/scripts\build.rb